name: flutterproject1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.0.2
  logger: ^2.4.0
  flutter_card_scanner: ^1.0.4
  permission_handler: ^11.3.1
  mobile_scanner: ^2.0.0
  google_ml_kit: ^0.7.0
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0+2
  camera_process: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
